### ISSUE TITLE
Expected an object with at least one key present

### ISSUE THREAD

**Issue by sethdorris** [armw4/node-postgres-patch#3]
Here is my code:

```js
var body = { teamName: 'new teamname', tag: 'tt' }
var output = patch(body);
```
 PatchError: expected an object with at least one key present

**Comment by armw4** [comment]
Yo, which version of node are you using?

**Comment by armw4** [comment]
I think you forgot to whitelist your keys. First parameter is the input object while second parameter is an array of valid keys or varargs so as to ensure only valid keys are extracted (prevents mass assignment). See the README for examples.

**Comment by sethdorris** [comment]
Yea I read the readme, but didn't realize the second parameter was for whitelisting keys, wasn't exactly clear. Can you update the docs to specify what the second parameter is for?

**Comment by armw4** [comment]
Sure I will try to make that clearer.

**Comment by armw4** [comment]
Closed via 33a57ba

**Comment by armw4** [comment]
@sethdorris This is resolved. I'll run npm audit soon to resolve any vulnerable packages. If any are identified it'll result in a major bump as it's been a few years I published a new patch, added a new feature, or pushed a major release (semver). Thank you for bringing this to my attention sir. Happy October 🍂 🎃

**Comment by armw4** [comment]
Looks like the Security tab allows you to enable __Automated security fixes__ via a software bot 🤖. I have that enabled now for this repository as well (e.g. Greenkeeper). Very nice indeed. 🎈
